bookshop:
  greeting: Welcome to the local book catalog!

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  jpa:
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: user 
    password: password
    url: jdbc:postgresql://localhost:5432/bookshopdb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

logging:
  level:
    sql: debug
    com.bladespring.bookshop.catalogservice: debug